/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex("movie").del();
  await knex("movie").insert([
    {
      id: "b5f37e47-40a7-4688-b6aa-420356eabcf8",
      title: "The shawshank redemption",
      year: 1994,
      daily_rental_rate: 100.0,
      discount_rate: 0,
      imdb_rating: 9.3,
      poster_url:
        "https://economictimes.indiatimes.com/thumb/msid-96406245,width-1600,height-900,resizemode-4,imgsize-71780/the-shawshank-redemption-where-to-watch-know-here.jpg?from=mdr",
      banner_url:
        "https://economictimes.indiatimes.com/thumb/msid-96406245,width-1600,height-900,resizemode-4,imgsize-71780/the-shawshank-redemption-where-to-watch-know-here.jpg?from=mdr",
      plot: `"The Shawshank Redemption" tells the story of Andy Dufresne, a banker who is wrongfully convicted of murder and sentenced to life in Shawshank State Penitentiary, where he forms a friendship with fellow inmate Red and ultimately engineers a daring escape over the course of two decades, all while maintaining his innocence. Through perseverance, hope, and resilience, Andy triumphs over adversity and finds redemption on the outside.`,
      runtime: "2h 22m",
      directed_by: "Frank Darabont",
      starring: "Tim Robbins,Morgan Freeman",
      release_at: "2022-04-14",
      is_deleted: false,
    },
    {
      id: "6ba1472e-563c-4dbd-ad31-d78aec32f5af",
      title: "The Godfather",
      year: 1972,
      daily_rental_rate: 150.0,
      discount_rate: 0,
      imdb_rating: 9.2,
      poster_url:
        "https://posters.movieposterdb.com/22_07/1972/68646/l_68646_8c811dec.jpg",
      banner_url:
        "https://c4.wallpaperflare.com/wallpaper/874/376/908/the-godfather-movies-vito-corleone-wallpaper-preview.jpg",
      plot: `"The Godfather" follows the story of the powerful Italian-American crime family, the Corleones, led by Don Vito Corleone. When the aging Don is nearly assassinated, his reluctant son, Michael, is drawn into the world of organized crime and eventually rises to power, navigating betrayal, loyalty, and vengeance in a ruthless quest to protect his family's legacy.`,
      runtime: "2h 55m",
      directed_by: "Francis Ford Coppola",
      starring: "AI Pacino,Marion Brando,James Caan",
      release_at: "2022-05-14",
      is_deleted: false,
    },
    {
      id: "e09ab8f1-bbd9-4066-a287-f31a54c2aef5",
      title: "The Godfather: Part II",
      year: 1974,
      daily_rental_rate: 150.0,
      discount_rate: 0,
      imdb_rating: 9.0,
      poster_url:
        "https://posters.movieposterdb.com/22_07/1974/71562/l_71562_28dbaac1.jpg",
      banner_url:
        "https://images.squarespace-cdn.com/content/v1/5b18735a3917ee20d18a2117/2a0760e9-95e0-4512-8b76-303a1202b77a/1-11132429479.jpg",
      plot: `The Godfather: Part II" continues the saga of the Corleone family, exploring the rise of a young Vito Corleone as he builds his criminal empire and the reign of his son, Michael, as he seeks to expand the family's influence and protect their legacy. As the story unfolds, the film delves into themes of power, corruption, and the consequences of violence, offering a compelling and complex portrait of the American dream and the cost of pursuing it.`,
      runtime: "3h 22m",
      directed_by: "Francis Ford Coppola",
      starring: "AI Pacino,Robert De Niro,Robert Duvall",
      release_at: "2023-03-29",
      is_deleted: false,
    },
    {
      id: "b349436c-a26a-4959-99af-7a1d9c4088fc",
      title: "The Dark Knight",
      year: 2008,
      daily_rental_rate: 125.0,
      discount_rate: 0,
      imdb_rating: 9.0,
      poster_url:
        "https://free-3dtextureshd.com/wp-content/uploads/2024/06/24.jpg.webp",
      banner_url:
        "https://free-3dtextureshd.com/wp-content/uploads/2024/06/24.jpg.webp",
      plot: `"The Dark Knight" follows the story of Batman as he faces off against the Joker, a sadistic criminal mastermind who seeks to undermine Gotham City's sense of justice and morality. As the Joker's reign of terror threatens to destroy the city, Batman must confront his own inner demons and make sacrifices to protect the people he loves. With its complex characters, intense action, and thought-provoking themes, "The Dark Knight" is a gripping exploration of heroism, villainy, and the blurred lines between them.`,
      runtime: "2h 32m",
      directed_by: "Christopher Nolan",
      starring: "Christian Bale,Heath Ledger,Aaron Eckhart",
      release_at: "2023-04-29",
      is_deleted: false,
    },
    {
      id: "ad41b6f6-d79f-4e58-89d6-9bb53498ccd9",
      title: "The Dark Knight Rises",
      year: 2012,
      daily_rental_rate: 125.0,
      discount_rate: 0,
      imdb_rating: 8.4,
      poster_url:
        "https://posters.movieposterdb.com/21_06/2012/1345836/l_1345836_429edb63.jpg",
      banner_url:
        "https://c4.wallpaperflare.com/wallpaper/727/965/131/batman-movies-film-batman-the-dark-knight-rises-cities-entertainment-movies-hd-art-wallpaper-preview.jpg",
      plot: `Eight years after the Joker's reign of anarchy, Batman, with the help of the enigmatic Catwoman, is forced from his exile to save Gotham City from the brutal
      guerr`,
      runtime: "2h 44m",
      directed_by: "Christopher Nolan",
      starring: "Christian Bale,Tom Hardy,Anne Hathaway",
      release_at: "2023-07-19T",
      is_deleted: false,
    },
    {
      id: "a742a595-e707-458a-9240-66742251dabf",
      title: "Spider Man 1",
      year: 2002,
      daily_rental_rate: 100.0,
      discount_rate: 0,
      imdb_rating: 7.3,
      poster_url:
        "https://posters.movieposterdb.com/08_10/2002/145487/l_145487_821ea90e.jpg",
      banner_url:
        "https://i.pinimg.com/originals/74/6d/79/746d79553f55de04e8f9560cb35d2e41.jpg",
      plot: `Peter Parker, a shy high school student, is often bullied by his classmates. However, his life changes when he is bitten by a genetically altered spider and gains superpowers. He must now use his newfound abilities to fight the evil Green Goblin and save the city.`,
      runtime: "2h 1m",
      directed_by: "Sam Raimi",
      starring: "Tobey Maguire,Kirsten Dunst,Willem Dafoe",
      release_at: "2023-08-25",
      is_deleted: false,
    },
    {
      id: "284db811-12a5-4cc9-b51b-fd5a0468ce6e",
      title: "Spider Man 2",
      year: 2004,
      daily_rental_rate: 100.0,
      discount_rate: 0,
      imdb_rating: 7.3,
      poster_url:
        "https://posters.movieposterdb.com/13_04/2004/316654/l_316654_ec1564ae.jpg",
      banner_url:
        "https://m.media-amazon.com/images/S/pv-target-images/1b5a47977489320f63ec82e39dc7377922f37de680cb9e4f76ed272aa5c9b533.jpg",
      plot: "Peter Parker, a.k.a. Spider man faces a new challenge as he battles Doctor Octopus, a scientist who has been transformed into a dangerous villain following a failed experiment.",
      runtime: "2h 7m",
      directed_by: "Sam Raimi",
      starring: "Tobey Maguire,Kirsten Dunst,Alfred Molina",
      release_at: "2023-10-30",
      is_deleted: false,
    },
    {
      id: "2d3e6418-34eb-4753-aae4-b45eb78acbed",
      title: "Harry Potter and the Sorcerer's Stone",
      year: 2001,
      daily_rental_rate: 100.0,
      discount_rate: 0,
      imdb_rating: 7.6,
      poster_url:
        "https://posters.movieposterdb.com/13_02/2001/241527/l_241527_da927a3d.jpg",
      banner_url: "https://picfiles.alphacoders.com/622/62263.jpg",
      plot: "Harry Potter, an orphaned child, discovers that he is a wizard and is invited to study at Hogwarts. Even as he escapes a dreary life and enters a world of magic, he finds trouble awaiting him.",
      runtime: "2h 32m",
      directed_by: "Chris Columbus",
      starring: "Daniel Radcliffe,Rupert Grint,Emma Watson",
      release_at: "2023-11-08",
      is_deleted: false,
    },
    {
      id: "f800a874-d19f-40e4-80af-778188705a44",
      title: "Harry Potter and the Chamber of Secrets",
      year: 2002,
      daily_rental_rate: 100.0,
      discount_rate: 0,
      imdb_rating: 7.4,
      poster_url:
        "https://posters.movieposterdb.com/11_08/2002/295297/l_295297_6be2c5d1.jpg",
      banner_url: "https://picfiles.alphacoders.com/620/62025.jpg",
      plot: "Harry ignores warnings not to return to Hogwarts, only to find the school plagued by a series of mysterious attacks and a strange voice haunting him.",
      runtime: "2h 41m",
      directed_by: "Chris Columbus",
      starring: "Daniel Radcliffe,Rupert Grint,Emma Watson",
      release_at: "2023-11-12",
      is_deleted: false,
    },
    {
      id: "e6f46ab0-67a4-4126-9b30-b8647a5e2856",
      title: "The Matrix",
      year: 1999,
      daily_rental_rate: 125.0,
      discount_rate: 0,
      imdb_rating: 8.7,
      poster_url:
        "https://posters.movieposterdb.com/06_01/1999/0133093/l_77607_0133093_ab8bc972.jpg",
      banner_url:
        "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRnW2auKIUMHvoiX-eTeVWTjXmHUb47Hi1lSRPCGDHlB6oMbkj3VpF1dhqQ6gtK-fqbzs&usqp=CAU",
      plot: `Thomas Anderson, a computer programmer, is led to fight an underground war against powerful computers who have constructed his entire reality with a system called the Matrix.`,
      runtime: "2h 16m",
      directed_by: "Lana Wachowski,Lilly Wachowski",
      starring: "Keanu Reeves,Laurence Fishburne,Carrie-Anne Moss",
      release_at: "2023-12-15",
      is_deleted: false,
    },
    {
      id: "47ef0a76-fbed-4d6f-bdd5-55ffc6506c03",
      title: "Happy Gilmore",
      year: 1996,
      daily_rental_rate: 100.0,
      discount_rate: 0,
      imdb_rating: 7.0,
      poster_url:
        "https://posters.movieposterdb.com/07_10/1996/116483/l_116483_181afe60.jpg",
      banner_url: "https://picfiles.alphacoders.com/963/96345.jpg",
      plot: "A rejected hockey player puts his skills to the golf course to save his grandmother's house.",
      runtime: "1h 32m",
      directed_by: "Dennis Dugan",
      starring: "Adam Sandler,Christopher McDonald,Julie Bowen",
      release_at: "2023-12-30",
      is_deleted: false,
    },
    {
      id: "7da10bde-8a57-491d-8da3-0660279fdc5e",
      title: "The Matrix Resurrections",
      year: 2021,
      daily_rental_rate: 150.0,
      discount_rate: 0,
      imdb_rating: 5.7,
      poster_url:
        "https://posters.movieposterdb.com/21_12/2021/10838180/l_10838180_1e7a1b6f.jpg",
      banner_url: "https://picfiles.alphacoders.com/106/106331.jpg",
      plot: 'The Matrix Resurrections" follows the story of Neo, a computer programmer who discovers that his reality is a simulated world created by machines to subdue humanity. As Neo awakens to the truth and joins a group of rebels, he must confront his past and the forces that seek to control him, leading to a final showdown that will determine the fate of both humans and machines.',
      runtime: "2h 28m",
      directed_by: "Lana Wachowski",
      starring: "Keanu Reeves,Carrie-Anne Moss,Yahya Abdul-Mateen II",
      release_at: "2024-01-15",
      is_deleted: true,
    },
    {
      id: "91ff065e-e390-4721-8b0e-1b3da38f5945",
      title: "American Sniper",
      year: 2014,
      daily_rental_rate: 150.0,
      discount_rate: 0,
      imdb_rating: 7.3,
      poster_url:
        "https://posters.movieposterdb.com/22_05/2014/2179136/l_2179136_e67933e8.jpg",
      banner_url:
        "https://static.thcdn.com/images/large/original//productimg/1600/1600/15278576-5465127341444934.jpg",
      plot: 'American Sniper" follows the story of Chris Kyle, a Navy SEAL sniper with the most confirmed kills in U.S. military history. As Kyle becomes a legend on the battlefield, he struggles to reconcile his military service with his family life, facing the challenges of war, trauma, and the toll of his actions on his mental and emotional well-being.',
      runtime: "2h 13m",
      directed_by: "Clint Eastwood",
      starring: "Bradley Cooper,Sienna Miller,Kyle Gallner",
      release_at: "2024-01-20",
      is_deleted: false,
    },
    {
      id: "e3d0cd0e-4150-4118-a227-329dfae69d9f",
      title: "Dune part 2",
      year: 2000,
      daily_rental_rate: 150.0,
      discount_rate: 0.15,
      imdb_rating: 8.2,
      poster_url:
        "https://image.tmdb.org/t/p/original/czembW0Rk1Ke7lCJGahbOhdCuhV.jpg",
      banner_url:
        "https://assets-prd.ignimgs.com/2023/12/03/dune-1701627712924.jpg",
      plot: `Dune: Part Two" continues the epic saga of Paul Atreides as he navigates the treacherous politics and power struggles of the desert planet Arrakis. As Paul embraces his destiny as the messiah of the Fremen people, he must confront the forces of the Empire and the malevolent Baron Harkonnen in a battle for control of the most valuable substance in the universe: the spice melange. With its stunning visuals, intricate world-building, and compelling characters, "Dune: Part Two" is a mesmerizing and thought-provoking exploration of power, destiny, and the human spirit.`,
      runtime: "2h 35m",
      directed_by: "Denis Villeneuve",
      starring: "Timothée Chalamet,Rebecca Ferguson,Jason Momoa",
      release_at: "2000-09-20",
      is_deleted: false,
    },
  ]);
}
